### ISSUE TITLE
Breaking change introduced in v4.25.1 by changing workflows

### ISSUE THREAD

**Issue by Viserius** [liquibase/liquibase-db2i#100]
Since version v4.25.1, liquibase-core has been removed from liquibase-db2i.
This is a breaking change, and should not be included in a patch update.
Note that this change is also not documented in the release notes.

Projects are impacted if they include liquibase-db2i and liquibase-core as a transitive dependency, and update their liquibase-db2i from v4.25.0 to v4.25.1. Then, liquibase-core is suddenly not on the classpath anymore and all sorts of things can go wrong.

The relevant commit: https://github.com/liquibase/liquibase-db2i/commit/d7e9e5a03ce2f84d9eaa3abfc6087894ef39b298#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8 (@jandroav)

P.S. each release contains release notes with a link to a diff/compare versions. This link is broken and does not work. For instance, the last release links to:
https://github.com/liquibase/liquibase-db2i/compare/v4.25.1...v4.26.0
which makes it seem as if there are no changes. This should be:
https://github.com/liquibase/liquibase-db2i/compare/liquibase-db2i-4.25.1...liquibase-db2i-4.26.0

**Comment by jandroav** [comment]
Hey @Viserius I think that is because of this line https://github.com/liquibase/liquibase-parent-pom/blob/65f8f273dac34b7f10ca513d0a032fb0dab7a7ec/pom.xml#L237

We will fix the scope for it and release a new version of the parent-pom

**Comment by jandroav** [comment]
@Viserius next extension release will include the new parent pom version: https://github.com/liquibase/liquibase-db2i/pull/102
