### ISSUE TITLE
DB2i supports modifying not null constraints

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase-db2i#2]
With a chanset that has the command addNotNullConstraint, when I run liquibase:update I got the error "DB2 versions less than 9 do not support modifying null constraints"

https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetNullableGenerator.java (line 41)

The database is db2 for iseries version V7R1M0 and it support add not null constraint.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-400) by [Unito](https://www.unito.io/learn-more)

**Comment by cplaetzinger** [comment]
How about building a new release? I'm running into the same issue and 1.1-SNAPSHOT fixed it.
