### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by thomseno** [liquibase/liquibase-db2i#8]
Hi @nvoxland,

some very important changes have been done since this first (and only) release of this extension. Is is about time for releasing a new version?

Regards, Oliver

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-398) by [Unito](https://www.unito.io/learn-more)

**Comment by jOphey** [comment]
Hi @nvoxland 

As one of the contributors I also just want to ask you to create a new release for the current codebase.
This would help us a lot with streamlining our dependencies.

Thanks in advance,
Jan

**Comment by r2liquibase** [comment]
This an old issue. If it continues to be a problem, please reopen. Thanks!
