### ISSUE TITLE
We can't run CL commands in our deployments

### ISSUE THREAD

**Issue by dave80439** [liquibase/liquibase-db2i#9]
When I run SQL using one of the IBM clients I am allowed to run a CL command.  The same syntax used in Liquibase doesn't work.  Is there another way to do the same thing?
Here is an example:
cl: GRTOBJAUT OBJ(<schema name>/<file name>) OBJTYPE(*FILE) AUTL(<AUTL NAME>)
This works fine using IBM's ACS software .

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-397) by [Unito](https://www.unito.io/learn-more)

**Comment by jOphey** [comment]
Try using
CALL GRTOBJAUT OBJ(/) OBJTYPE(*FILE) AUTL()
as statement in Liquibase.
I'm currently not at work, but I think this did the trick for us.
I can have a look tomorrow, when I'm back in office, if this doesn't work.

**Comment by dave80439** [comment]
Jan,
               I can’t seem to get anyone to try this command.  Sorry I don’t have the ability to use Liquibase this is something our Java developers do.  I just want them to restore authorities in changes where they drop files.
Just the same you are aware I am asking a to run a command and not a Service Program?
Let me know thx,

Dave Olson     Senior iSeries Engineer  ITS
Colorado Judicial Branch
Office 720-625-5533
Cell      303-618-9811
[cid:image003.jpg@01D5DB4A.FC3210A0]

**Comment by jOphey** [comment]
I just had a quick look at our code:

We use something like
CALL QSYS.QCMDEXEC('DLTLIB SOMELIB')
as SQL-Statement in order to execute commands normally executed via VT5250 terminal.

I'm not an iSeries-specialist, but only java-developer. I cannot say, if there is any further configuration on iSeries neccessary to be able to execute commands via SQL in this way.

Sorry for the former incomplete hint.

**Comment by dave80439** [comment]
Jan,
No worries for earlier response I see this is the Qcmdexec API I take it this works?
Thx for the help,

Sent from my iPhone

On Feb 5, 2020, at 2:48 AM, Jan Ophey <notifications@github.com> wrote:

﻿

I just had a quick look at our code:

We use something like
CALL QSYS.QCMDEXEC('DLTLIB SOMELIB')
as SQL-Statement in order to execute commands normally executed via VT5250 terminal.

I'm not an iSeries-specialist, but only java-developer. I cannot say, if there is any further configuration on iSeries neccessary to be able to execute commands via SQL in this way.

Sorry for the former incomplete hint.
